[project]
name = "eval-service"
version = "0.1.0"
description = "Servicio de evaluación"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"
