[project]
name = "feria-sdk"
version = "0.1.0"
description = "SDK de clientes"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = []
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
