[project]
name = "event-bus"
version = "0.1.0"
description = "Bus de eventos"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"
