[project]
name = "api-gateway"
version = "0.2.0"
description = "Gateway HTTP ligero"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
