[project]
name = "feria-agent"
version = "0.1.0"
description = "Planner y políticas del agente"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"
