[project]
name = "cpu-worker"
version = "0.1.0"
description = "CPU worker"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"
