[project]
name = "feria-observability"
version = "0.1.0"
description = "Exporters y reglas de anomalías"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"
