[project]
name = "orchestrator"
version = "0.1.0"
description = "Control plane"
requires-python = ">=3.11"
dependencies = ["apscheduler>=3.10"]

[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"
