[project]
name = "observability-service"
version = "0.1.0"
description = "Servicio de observabilidad"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = []
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
