[project]
name = "feria-core"
version = "0.1.0"
description = "Utilidades compartidas del núcleo"
requires-python = ">=3.11"
dependencies = ["pydantic>=2.7"]

[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"
