[project]
name = "feria-policy"
version = "0.1.0"
description = "Validadores de políticas"
requires-python = ">=3.11"

[build-system]
requires = []
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
