apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: feria
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "api-gateway"
        static_configs:
          - targets: ["api-gateway:8000"]
      - job_name: "orchestrator"
        static_configs:
          - targets: ["orchestrator:9000"]
