[defaults]
small = "phi-3.5-mini"
medium = "llama3.1:8b-instruct"
large = "qwen2.5-coder:14b"

[rules]
low_diff = { max_score = 2.9, model = "small" }
mid_diff = { min_score = 3.0, max_score = 5.9, model = "medium" }
high_diff = { min_score = 6.0, model = "large" }

[ab_test]
canary_percentage = 0.15
