apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feria

resources:
  - ../../base/namespace.yaml
  - ../../base/gateway.yaml
  - ../../base/prometheus/prom.yaml
  - ../../base/prometheus/rules/alerts.yaml
  - ../../base/nats/nats.yaml

patchesStrategicMerge:
  - replica-overrides.yaml
