name: Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
  pull_request:
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
      - name: Spell check
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: cspell.json
          files: |
            README.md
            docs/**/*.md
