name: Nightly Eval

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v1
      - name: Sync dependencies
        run: uv sync
      - name: Run nightly evaluation
        run: uv run python scripts/eval_nightly.py --report docs/reports/nightly-latest.md
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: nightly-report
          path: docs/reports/nightly-latest.md
