name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (vX.Y.Z)'
        required: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v1
      - name: Sync dependencies
        run: uv sync
      - name: Run smoke tests
        run: uv run make test
      - name: Build artifacts
        run: uv build
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: dist/*
